### ISSUE TITLE
There's no src folders ???

### ISSUE THREAD

**Issue by ramalchamuditha** [minidu97/android#1]

**Comment by minidu97** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Cannot upload those files bro.. Permissions are not allowed                                                                                                                                              Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: August 27, 2019 12:36 PMTo: android@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [minidu97/android] There's no src folders ??? (#1)
